garvbox/gitopsokat

- apps/base/plexmediaserver.yaml
Switch plex over to beta package channel for early update access
> Plex Beta Channel

- apps/base/factorio.yaml
- apps/gammasite-prod/deluge-patch-values.yaml
- apps/gammasite-prod/factorio/patch-values.yaml
- apps/gammasite-prod/factorio/server-config-secret.yaml
- apps/gammasite-prod/kustomization.yaml
- apps/testsite/kustomization.yaml
- clusters/gammasite-prod/apps.yaml
- clusters/gammasite-prod/infrastructure.yaml
- clusters/testsite/flux-system/gotk-sync.yaml
* Factorio server deployment on gammasite
* Basic experimental setup with initial config
* No Automatic save creation, saves will need to be added manually
> Factorio Server Deployment

- apps/base/factorio.yaml
- apps/gammasite-prod/factorio/patch-values.yaml
Updating run user etc around permissions issues
> [apps] Update factorio secret mount

- apps/gammasite-prod/kustomization.yaml
Permissions issues and storage causing problems
may need to build a custom factorio image on a cleaner setup
> [apps] Temp disable factorio

- apps/base/grafana.yaml
Grafana login is pretty robust, no issues exposing it.
> [apps] Expose Grafana outside of LAN

- apps/base/syncthing.yaml
- apps/gammasite-prod/kustomization.yaml
- apps/gammasite-prod/syncthing-patch-values.yaml
- clusters/gammasite-prod/apps.yaml
- clusters/gammasite-prod/infrastructure.yaml
Basic initial setup to test out sync to Ark
> [apps] Deploy Syncthing

- apps/base/radarr.yaml
- apps/base/sonarr.yaml
- apps/base/syncthing.yaml
- apps/base/tautulli.yaml
These apps should be pretty safe to expose with password protection
> [apps] Disable LAN Proxy restrictions for Arrs

- apps/base/unpackerr.yaml
- apps/gammasite-prod/kustomization.yaml
- apps/gammasite-prod/storage-patch-values.yaml
- apps/gammasite-prod/unpackerr/config-secret.yaml
- apps/gammasite-prod/unpackerr/patch-values.yaml
Initial deployment and configuration to test automatic extraction
> [apps] Unpackerr Deployment

- apps/base/deluge.yaml
- apps/base/unifi.yaml
- apps/base/whoami.yaml
- apps/gammasite-prod/kustomization.yaml
- clusters/gammasite-prod/apps.yaml
- clusters/gammasite-prod/infrastructure.yaml
Initial deployment based on basic docker setup
Includes change to clean up source whitelisting
> [apps] Deploy Unifi Controller

- .github/workflows/yaml-lint.yaml
- .pre-commit-config.yaml
- apps/base/homeassistant.yaml
Config doesnt change often and changes can be managed by attaching to pod with vscode, removing wasted resources
> [apps] Remove HA Code-server

- infrastructure/testsite/kustomization.yaml
- infrastructure/testsite/postgres-patch-values.yaml
Preparing test PG for deployment
> [infra] Single Postgres DB on staging

- .github/renovate.json
> [ci] Allow dep patches auto branch merge

- apps/gammasite-prod/patch-values.yaml
- clusters/gammasite-prod/apps.yaml
- clusters/gammasite-prod/infrastructure.yaml
Reverts garvbox/gitopsokat#196
> Revert "Add a service for Philips Hue emulation on HA"

- apps/base/esphome.yaml
- apps/gammasite-prod/config-vols.yaml
- apps/gammasite-prod/patch-values.yaml
ESPHome Dashboard server with persistent config vols and frontend config. Copied from HomeAssistant
> Add ESPHome Deployment

- .pre-commit-config.yaml
- apps/base/audiobookshelf.yaml
- apps/gammasite-prod/config-vols.yaml
- apps/gammasite-prod/kustomization.yaml
- apps/gammasite-prod/patch-values.yaml
Include dev branch patches and WIP audiobookshelf deployment
> Add Audiobookshelf

- infrastructure/extras/nvidia-device-plugin/helmrelease.yaml
Reverts garvbox/gitopsokat#627 due to issues on teslatron
> Revert "Update Helm release nvidia-device-plugin to v0.15.0"

- apps/teslops/frigate/patch.yaml
Older cameras struggle with dual stream support
> Changed older cameras to use just the 1 stream

- apps/base/prowlarr.yaml
- apps/base/radarr.yaml
- apps/base/sonarr.yaml
Cuts down on the churn and they dont change that much
> Switch 'arrs to stable releases

- apps/base/tautulli.yaml
Updated start args as hinted [here](https://github.com/Tautulli/Tautulli/pull/2301#issuecomment-2054107140)
> Switch to main tautulli image

- apps/gammasite-prod/kustomization.yaml
- apps/gammasite-prod/nextcloud/kustomization.yaml
- apps/gammasite-prod/nextcloud/patch.yaml
- apps/gammasite-prod/nextcloud/pvc.yaml
let's see how it handles the mighty Air Pro
> NextCloud returns

- apps/base/mosquitto.yaml
- apps/deltasite/kustomization.yaml
- apps/deltasite/mosquitto/kustomization.yaml
- apps/deltasite/mosquitto/patch.yaml
- clusters/deltasite/apps.yaml
Restore previous base config, updated for newer app-template, and add
deltasite deploy
> Add Mosquitto deployment

- apps/gammasite-prod/jellyfin/patch.yaml
- apps/gammasite-prod/plexmediaserver/patch.yaml
- **Remove GPU from gammatron Plex**
- **Add gpu resources to jellyfin**
> Move Intel GPU from Plex to Jellyfin

- apps/gammasite-prod/kustomization.yaml
- apps/sources/cnpg-charts.yaml
- **Add cloudnative postgres chart**
- **Add postgres data PV**
- **Update cluster path**
- **Add basic cluster config**
- **Use existing claim in cluster**
- **Include PG cluster in config**
- **Fix PG chart source**
> CNPG Source fixes

- apps/sources/bjw-s-charts.yaml
Mirror upstream location change
> Update path to bjw-s charts repository

- apps/base/radarr.yaml
Experimental change to verify the setup before moving the rest
> Move to home-ops radarr image

- .github/renovate.json
- apps/base/plexmediaserver.yaml
- apps/base/prowlarr.yaml
- apps/base/sonarr.yaml
- apps/base/unpackerr.yaml
- **Udpate upstream repo paths for renovate**
- **Switch unpackerr image to native build**
- **Switch sonarr to new upstream**
- **Switch prowlarr to new upstream**
- **Switch plex to new upstream**
> Switch all onedr0p images to new upstream location

- apps/gammasite-prod/homeassistant/ingress.yaml
- apps/gammasite-prod/homeassistant/kustomization.yaml
- apps/gammasite-prod/homeassistant/service.yaml
- apps/gammasite-prod/kustomization.yaml
- **Revert "Remove homeassistant Forward"**
- **Update homeassistant target**
> reinstate ha forward

- apps/base/deluge.yaml
- apps/gammasite-prod/radarr/patch.yaml
- apps/gammasite-prod/sonarr/patch.yaml
Bringing back up deluge and the 'arrs. Syncthing and plex remaining
offline for now pending what to do with remote connections
> Scale back up downloading services
